# Generated by Django 2.2.5 on 2020-03-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128, null=True, unique=True)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('license', models.CharField(max_length=30, null=True)),
                ('car_make', models.CharField(max_length=30, null=True)),
                ('car_model', models.CharField(max_length=30, null=True)),
                ('car_year', models.IntegerField(null=True)),
                ('car_colour', models.CharField(max_length=30, null=True)),
                ('car_county', models.CharField(max_length=30, null=True)),
                ('car_plate', models.CharField(max_length=30, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('group', models.IntegerField()),
            ],
        ),
    ]
